quarkus.package.jar.type=legacy-jar

# TODO native
#quarkus.package.jar.enabled=false
#quarkus.native.enabled=true

# TODO read database credentials
#%lambda.quarkus.vault.credentials-provider.db.kv-path=myapps/vault-quickstart/db
#%lambda.quarkus.datasource.credentials-provider=db

quarkus.test.integration-test-profile=integration-test
