FROM public.ecr.aws/lambda/provided:al2-x86_64

# Install Java
RUN yum install -y java-21-amazon-corretto

COPY target/quarkus-app/ ${LAMBDA_RUNTIME_DIR}/

# Create bootstrap for Quarkus
RUN echo "#!/bin/bash" >> ${LAMBDA_RUNTIME_DIR}/bootstrap
RUN echo "cd ${LAMBDA_RUNTIME_DIR}" >> ${LAMBDA_RUNTIME_DIR}/bootstrap
RUN echo "exec java -jar quarkus-run.jar" >> ${LAMBDA_RUNTIME_DIR}/bootstrap

RUN chmod +x ${LAMBDA_RUNTIME_DIR}/bootstrap
#FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5 as packages

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

# for JasperReports
RUN microdnf update -y && microdnf install -y freetype fontconfig && microdnf clean all

#FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

# TODO switch back to ubi-minimal image, copy all needed libraries from builder
# for indigo-renderer (likely the same will be needed for JasperReports)
#COPY --from=packages \
#   /lib64/libpng16.so.16 \
#   /lib64/libfreetype.so.6 \
#   /lib64/libbz2.so.1 \
#   /lib64/libxml2.so.2 \
#   /lib64/
#COPY --from=packages \
#   /usr/lib64/libfontconfig.so.1 \
#   /usr/lib64/libbrotlicommon.so.1 \
#   /usr/lib64/libgraphite2.so.3 \
#   /usr/lib64/libharfbuzz-gobject.so.0 \
#   /usr/lib64/libharfbuzz-subset.so.0 \
#   /usr/lib64/libharfbuzz.so.0 \
#   /usr/lib64/libbrotlicommon.so.1 \
#   /usr/lib64/libbrotlidec.so.1 \
#   /usr/lib64/libbrotlienc.so.1 \
#   /usr/lib64/
#COPY --from=packages /etc/fonts/conf.d/ /etc/fonts/conf.d/
#COPY --from=packages /usr/share/fontconfig/conf.avail/ /usr/share/fontconfig/conf.avail/

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root build/nativelibs/linux-x86_64/* /work/nativelibs/linux-x86_64/
COPY --chown=1001:root build/*runner* /work/application

# Enable IPv6 in the container
RUN echo 'net.ipv6.conf.all.disable_ipv6 = 0' >> /etc/sysctl.conf
RUN echo 'net.ipv6.conf.default.disable_ipv6 = 0' >> /etc/sysctl.conf

EXPOSE 8080
USER 1001

ENV NATIVE_LIB_PATH=/work/nativelibs
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djava.net.preferIPv6Addresses=true"]
