services:

  postgres:
    image: indigo-eln-postgres:built
    build:
      context: ../../postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eln
    volumes:
      - "../../../deployment-compose/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "35432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: 60s
      interval: 10s
      retries: 3
      start_interval: 1s

  eln-service:
    image: "indigoeln/eln-service:built"
    build:
      context: ../../eln/eln-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_PROFILE: integration-test
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/eln"
      QUARKUS_DATASOURCE_USERNAME: postgres  # TODO use eln user
      QUARKUS_DATASOURCE_PASSWORD: postgres
      ELN_API_SECRET: integrationTestsAPISecret
      QUARKUS_OIDC_AUTH_SERVER_URL: "http://keycloak:8080/realms/indigo-eln"
      QUARKUS_OIDC_CLIENT_ID: indigo-eln-client
      QUARKUS_OIDC_DISCOVERY_ENABLED: "false"
      QUARKUS_OIDC_JWKS_PATH: "protocol/openid-connect/certs"
      QUARKUS_OIDC_TOKEN_ISSUER: "any"
      QUARKUS_TLS_TRUST_ALL: true
      QUARKUS_REST_CLIENT_REPORTS_API_URL: "http://nginx:80/"
      QUARKUS_REST_CLIENT_SIGNATURE_API_URL: "http://nginx:80/"
      QUARKUS_REST_CLIENT_LOGGING_SCOPE: "request-response"
      QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT: "9999"
      QUARKUS_REST_CLIENT_EXTENSIONS_API_SCOPE: "all"
      QUARKUS_LOG_CONSOLE_FORMAT: "[ELN] %d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      QUARKUS_LOG_LEVEL: DEBUG
#      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dquarkus.profile=dev"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      keycloak-config-cli:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready" ]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s
    ports:
      - "38081:8080"
#      - "39080:5005"

  reports-service:
    image: "indigoeln/reports-service:built"
    build:
      context: ../../reports/reports-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_PROFILE: integration-test
      ELN_API_SECRET: integrationTestsAPISecret
      QUARKUS_LOG_CONSOLE_FORMAT: "[REPORTS] %d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      QUARKUS_LOG_LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__NET_SF_JASPERREPORTS__LEVEL: INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready" ]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s
    ports:
      - "38082:8080"

  signature-service:
    image: "indigoeln/signature-service:built"
    build:
      context: ../../signature/signature-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_PROFILE: integration-test
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/signature"
      QUARKUS_DATASOURCE_USERNAME: signature
      QUARKUS_DATASOURCE_PASSWORD: signature
      ELN_API_SECRET: integrationTestsAPISecret
      QUARKUS_OIDC_AUTH_SERVER_URL: "http://keycloak:8080/realms/indigo-eln"
      QUARKUS_OIDC_CLIENT_ID: indigo-eln-client
      QUARKUS_OIDC_DISCOVERY_ENABLED: "false"
      QUARKUS_OIDC_JWKS_PATH: "protocol/openid-connect/certs"
      QUARKUS_OIDC_TOKEN_ISSUER: "any"
      QUARKUS_TLS_TRUST_ALL: true
      # ELN_SIGNATURE_KEYSTORE_PATH: "/keystore.p12"
      ELN_SIGNATURE_KEYSTORE_PASSWORD: "1234"
      QUARKUS_LOG_CONSOLE_FORMAT: "[SIGNATURE] %d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      QUARKUS_REST_CLIENT_ELN_INTERNAL_API_URL: "http://nginx:80/"
      QUARKUS_REST_CLIENT_LOGGING_SCOPE: "request-response"
      QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT: "9999"
      QUARKUS_REST_CLIENT_EXTENSIONS_API_SCOPE: "all"
      QUARKUS_LOG_LEVEL: DEBUG
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      keycloak-config-cli:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready" ]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s
    ports:
      - "38083:8080"

  keycloak:
    image: indigoeln/keycloak:built
    build:
      context: ../../../deployment-compose/keycloak
      dockerfile: Dockerfile
    command: start-dev --health-enabled=true --log-level=ERROR 
    environment:
      KC_DB: postgres
      KC_HOSTNAME: localhost
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_MANAGEMENT_PORT: 9005
      KC_HTTP_MANAGEMENT_HEALTH_ENABLED: true
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - "38000:8080"
      - "39005:9005"

  keycloak-healthcheck:
    image: alpine:latest
    depends_on:
      - keycloak
    entrypoint: >
      /bin/sh -c "
      while ! wget -q -O- http://keycloak:9005/health/started; do
        echo waiting for keycloak;
        sleep 1;
      done;
      echo keycloak is up;
      tail -f /dev/null      
      "
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://keycloak:9005/health/ready || (echo 'Health check failed' >> /var/log/healthcheck.log && exit 1)"]
      interval: 1s
      timeout: 10s
      retries: 30

  keycloak-config-cli:
    image: quay.io/adorsys/keycloak-config-cli:6.4.0-26.1.0
    depends_on:
      - keycloak-healthcheck
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 150s
      IMPORT_VARSUBSTITUTION_ENABLED : true
      IMPORT_FILES_LOCATIONS: '/config/realm-config.json'
    volumes:
      - ../../../deployment-compose/keycloak-config-cli/realm-config.json:/config/realm-config.json

  nginx:
    image: nginx:alpine
    volumes:
      - ../../../deployment-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "38080:80"
    depends_on:
      - eln-service
