ALTER TABLE Experiment_Revision ADD COLUMN messages VARCHAR(1024)[];
ALTER TABLE Experiment ADD COLUMN version INT;

ALTER TABLE Compound ALTER COLUMN mol_weight TYPE DOUBLE PRECISION;
ALTER TABLE Compound ALTER COLUMN exact_mass TYPE DOUBLE PRECISION;

ALTER TYPE Application_Permission ADD VALUE 'SIGN_EXPERIMENTS';
