services:

  eln-service:
    build:
      context: ./eln/eln-service
      dockerfile: Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/eln"
      QUARKUS_DATASOURCE_USERNAME: eln
      QUARKUS_DATASOURCE_PASSWORD: eln
      ELN_COGNITO_USER_POOL_ID: xxx
      ELN_API_SECRET: apiSecret
      ELN_INTERNAL_API_SECRET: internalApiSecret
      QUARKUS_REST_CLIENT_REPORTS_API_URL: http://reports-service:8080
#      QUARKUS_REST_CLIENT_LOGGING_SCOPE: request-response
#      QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT: "9999"
#      QUARKUS_REST_CLIENT_EXTENSIONS_API_SCOPE: "all"
      QUARKUS_OIDC_AUTH_SERVER_URL: "https://keycloak.indigoeln.local:8443/realms/indigo-eln"
      QUARKUS_OIDC_CLIENT_ID: indigo-eln-client
      QUARKUS_TLS_TRUST_ALL: true
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      keycloak.indigoeln.local:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready"]
    ports:
      - "10020:8080"
      - "10021:5005"

  #  whoami:
#    image: containous/whoami
#
  postgres:
    image: public.ecr.aws/m5k0g6n7/indigoeln/indigo-eln-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./local/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: 60s
      start_interval: 1s

  keycloak.indigoeln.local:
    build:
        context: ./local/keycloak
        dockerfile: Dockerfile
    environment:
      KC_DB: postgres
      KC_HOSTNAME: keycloak.indigoeln.local
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
#      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      start_period: 120s
      start_interval: 1s
    ports:
#      - "8080:8080"
      - "8443:8443"

  # add frontend:
  # directory indigo-frontend
  # npm ci
  # npm run build

  # replace with nginx?
  traefik:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./local/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./local/traefik/services.yaml:/etc/traefik/services.yaml:ro"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
