quarkus.package.jar.type=legacy-jar

quarkus.native.container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25
quarkus.native.native-image-xmx=32G

quarkus.ssl.native=true

quarkus.flyway.migrate-at-start=false

quarkus.datasource.jdbc.min-size=1
quarkus.lambda-http.enable-security=true
quarkus.snapstart.enabled=false
