server {
    listen 80;
    server_name localhost;

    client_max_body_size 50m;

    # Frontend: Serve the UI
#     location / {
#         proxy_pass http://frontend:4200;
#         proxy_set_header Host $host;
#     }

    location /api/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /internalapi/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /openapi/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /swagger/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /internalapi/reports/ {
        proxy_pass http://reports-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /openapi/reports/ {
        proxy_pass http://reports-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /swagger/reports/ {
        proxy_pass http://reports-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /internalapi/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /openapi/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /swagger/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
