server {
    listen 80;
    server_name localhost;

    client_max_body_size 50m;

    # Frontend: Serve the UI
    location / {
        proxy_pass http://frontend:4200;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-API-Secret apiSecret;
    }
    location /internalapi/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-API-Secret apiSecret;
    }
    location /openapi/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /swagger/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-API-Secret apiSecret;
    }
    location /openapi/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /swagger/signature/ {
        proxy_pass http://signature-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /internalapi/reports/ {
        proxy_pass http://reports-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-API-Secret apiSecret;
    }
}
