server {
    listen 80;
    server_name localhost;

    # Frontend: Serve the UI
    location / {
        proxy_pass http://frontend:4200;
        proxy_set_header Host $host;
    }

    # Backend: Route any request starting with /api to the backend
    location /api/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /swagger/eln/ {
        proxy_pass http://eln-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}