version: "3.3"
services:
  mongo-db:
    image: mongo:3.4.17
    restart: always
    ports:
      - "27017:27017"

  postgres:
    build: ./signature/database
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  bingodb:
    build: ./bingodb
    environment:
      - SECURITY_USER_NAME=bingo
      - SECURITY_USER_PASSWORD=pass
      - SPRING_HOST=0.0.0.0
    ports:
      - "9999:9999"

  server:
    build: ./server
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/indigoeln
      # URL for BingoDB api
      - BINGODB_API_URL=http://bingodb:9999/api
      # Username to access BingoDB api
      - BINGODB_USERNAME=bingo
      # Password to access BingoDB api
      - BINGODB_PASSWORD=pass
      # allow cors for UI
      - CORS_ORIGIN=http://localhost:9000
      # user/password = admin/admin
      - DEFAULT_ADMIN_PASSWORD=$$2a$$10$$jawSRFtkzurLE2mDbiAK0O3MDtxvBi1OlbJV8HLFKKpIUC/I7Gyrq
      - SPRING_PROFILES_ACTIVE=cors
      - SPRING_HOST=0.0.0.0
      - SIGNATURESERVICE_URL=http://signature:8080/signatureservice
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    expose:
      - "8080"
      - "5005"
    ports:
      - "8080:8080"
      - "5005:5005"

  indigoeln-ui:
    build: ./ui
    environment:
      #      - INDIGOELN_SERVER=https://edge.aws.cloud-pipeline.com/pipeline-61766-8080-0/api/
      - INDIGOELN_SERVER=http://localhost:8080/api/
    expose:
      - "9000"
    ports:
      - "9000:9000"

  signature:
    build: ./signature
    environment:
      - DATABASE_CONNECTION_URL=jdbc:postgresql://postgres:5432/postgres
    expose:
      - "8080"
    ports:
      - "28080:8080"

