version: "3.3"
services:
  mongo-db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: /var/local/indigoeln/mongo-db
        target: /data/db

  postgres-signature:
    build: ./signature/database
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /var/local/indigoeln/postgres-signature
        target: /var/lib/postgresql/data

  postgres-crs:
    build: ./crs/database
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - type: bind
        source: /var/local/indigoeln/postgres-crs
        target: /var/lib/postgresql/data

  bingodb:
    build: ./bingodb
    environment:
      - BINGO_USERNAME=bingo
      - BINGO_PASSWORD=pass
      - SPRING_HOST=0.0.0.0
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Djna.debug_load=true -Djna.debug_load.jna=true
      - INDIGOELN_LIBRARY_PATH=/tmp/indigolibs
      - LD_LIBRARY_PATH=/tmp/indigolibs/linux-x86_64
    expose:
      - "9999"
      - "5005"
    ports:
      - "9999:9999"
#      - "5005:5005"
    volumes:
      - type: bind
        source: /var/local/indigoeln/bingodb
        target: /opt/jars/bingo

  server:
    build: ./server
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/indigoeln
      # URL for BingoDB api
      - BINGODB_API_URL=http://bingodb:9999/api
      # Username to access BingoDB api
      - BINGODB_USERNAME=bingo
      # Password to access BingoDB api
      - BINGODB_PASSWORD=pass
      # allow cors for UI
      - CORS_ORIGIN=http://localhost:9000
      # user/password = admin/admin
      - DEFAULT_ADMIN_PASSWORD=$$2a$$10$$jawSRFtkzurLE2mDbiAK0O3MDtxvBi1OlbJV8HLFKKpIUC/I7Gyrq
      - SPRING_PROFILES_ACTIVE=cors
      - SPRING_HOST=0.0.0.0
      - SIGNATURESERVICE_URL=http://signature:8080/signatureservice
      - INDIGOELN_CLIENT_SIGNATURESERVICE_URL=http://localhost:28080/signatureservice
      - CRS_SEARCH_SERVICE_URL=http://crs:8080/crs/service/search
      - CRS_REGISTRATION_SERVICE-URL=http://crs:8080/crs/service/registration
      - CRS_USERNAME=user
      - CRS_PASSWORD=pass

      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - INDIGOELN_LIBRARY_PATH=/tmp/indigolibs
      - LD_LIBRARY_PATH=/tmp/indigolibs/linux-x86_64

    expose:
      - "8080"
      - "5005"
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - type: bind
        source: /mnt/c/Work/IndigoELN/Indigo/dist/lib
        target: /tmp/indigolibs

#  indigoeln-ui:
#    build: ./ui
#    environment:
#      - INDIGOELN_SERVER=http://localhost:8080/api/
#    expose:
#      - "9000"
#    ports:
#      - "9000:9000"

  signature:
    build: ./signature
    environment:
      - DATABASE_CONNECTION_URL=jdbc:postgresql://postgres-signature:5432/postgres
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    expose:
      - "8080"
      - "5005:5005"
    ports:
      - "28080:8080"
#      - "5005:5005"

  crs:
    build: ./CRS
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres-crs:5432/postgres
    expose:
      - "8080"
    ports:
      - "38080:8080"
