version: "3.3"
services:
  mongo-db:
    image: mongo:3.4.17
    restart: always
    ports:
      - "27017:27017"

  postgres:
    build: ./IndigoSignatureService/database
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  bingodb:
    build: ./bingodb
    environment:
      - security.user.name=bingo
      - security.user.password=pass
      - spring.host=0.0.0.0
    ports:
      - "9999:9999"

  server:
    build: ./server
    environment:
      - spring.data.mongodb.uri=mongodb://mongo-db:27017/indigoeln
      # URL for BingoDB api
      - bingodb.api-url=http://bingodb:9999/api
      # Username to access BingoDB api
      - bingodb.username=bingo
      # Password to access BingoDB api
      - bingodb.password=pass
      # allow cors for UI
      - cors.origin=https://edge.aws.cloud-pipeline.com
      # user/password = admin/admin
      - default-admin-password=$$2a$$10$$jawSRFtkzurLE2mDbiAK0O3MDtxvBi1OlbJV8HLFKKpIUC/I7Gyrq
      - spring.profiles.active=cors
      - spring.host=0.0.0.0
      - signatureservice.url=http://signature:8080/signatureservice
      - JAVA_OPTS=-Djna.debug_load=true -Djna.debug_load.jna=true -Djna.library.path=/lib;/usr/lib;/lib64;/usr/lib64
      - LD_LIBRARY_PATH=/usr/lib64
      #-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    expose:
      - "8080"
    ports:
      - "18080:8080"

  ui:
    build: ./ui
    environment:
      - INDIGOELN_SERVER=https://edge.aws.cloud-pipeline.com/pipeline-61766-8080-0/api/
    expose:
      - "19000"
    ports:
      - "19000:9000"

  signature:
    build: ./IndigoSignatureService
    environment:
      - database-connection-url=jdbc:postgresql://postgres:5432/postgres
    expose:
      - "8080"
    ports:
      - "28080:8080"

  nginx:
    build: ./nginx
    command: [ nginx-debug, '-g', 'daemon off;' ]
    expose:
      - "80"
    ports:
      - "8080:80"
