quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.physical-naming-strategy=io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
quarkus.hibernate-orm.validate-in-dev-mode=false
jakarta.persistence.schema-generation.database.action=none
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.unsupported-properties."hibernate.criteria.literal_handling_mode"=bind

%devtest.jakarta.persistence.schema-generation.database.action=validate
%integration-test.jakarta.persistence.schema-generation.database.action=none
%devtest.quarkus.hibernate-orm.database.generation=validate
%integration-test.quarkus.hibernate-orm.database.generation=none
%devtest.quarkus.flyway.migrate-at-start=true
%integration-test.quarkus.flyway.migrate-at-start=false

%test.quarkus.hibernate-orm.statistics=true
