# Gradle properties

quarkusPluginId=io.quarkus
quarkusPluginVersion=3.23.4
quarkusPlatformGroupId=io.quarkus
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.23.4
quarkusAmazonServicesVersion=3.23.4

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx1g
