# Gradle properties

quarkusPluginId=io.quarkus
quarkusPluginVersion=3.36.0.CR1
quarkusPlatformGroupId=io.quarkus
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.36.0.CR1
quarkusAmazonServicesVersion=3.36.0.CR1

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
