#quarkus.package.jar.type=legacy-jar

#quarkus.container-image.build=true
quarkus.container-image.build=false
quarkus.native.enabled=true
quarkus.native.container-build=true
#quarkus.native.remote-container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-24
quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna
quarkus.package.jar.enabled=false

quarkus.datasource.devservices.port=15434
