AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:

  Api: # workaround to make SAM work with binary data, see https://github.com/aws/aws-sam-cli/issues/3110
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - "*~1*"   # SAM local requires ~ instead of / in media types
      StageName: dev

  ElnLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: indigoeln/eln-lambda:built.integrationtests
      Environment:
        Variables:
          QUARKUS_PROFILE: "integration-test"
          QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://172.17.0.1:25432/eln"
          QUARKUS_DATASOURCE_USERNAME: "eln"
          QUARKUS_DATASOURCE_PASSWORD: "eln"
          ELN_COGNITO_USER_POOL_ID: "xxx"
          ELN_API_SECRET: "integrationTestsAPISecret"
          ELN_STORAGE_S3_BUCKET: "indigoeln-data"
          QUARKUS_S3_ENDPOINT_OVERRIDE: "http://172.17.0.1:4566"
          QUARKUS_S3_PATH_STYLE_ACCESS: "true"
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
          QUARKUS_REST_CLIENT_REPORTS_API_URL: "http://172.17.0.1:28080/"
          QUARKUS_REST_CLIENT_SIGNATURE_API_URL: "http://172.17.0.1:28080/"
          QUARKUS_REST_CLIENT_LOGGING_SCOPE: "request-response"
          QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT: "9999"
          QUARKUS_REST_CLIENT_EXTENSIONS_API_SCOPE: "all"
          QUARKUS_LOG_CONSOLE_FORMAT: "[ELN] %d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
          QUARKUS_LOG_LEVEL: INFO # DEBUG
      Events:
        API:
          Type: HttpApi
          Properties:
            Path: /api/eln/{proxy+}
            Method: ANY
        InternalAPI:
          Type: HttpApi
          Properties:
            Path: /internalapi/eln/{proxy+}
            Method: ANY
    Metadata:
      DockerContext: ../../eln/eln-lambda/build
      Dockerfile: ../../eln/eln-lambda/src/main/docker/Dockerfile.native.integrationtests
      DockerTag: built.integrationtests

  ReportsLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: indigoeln/reports-lambda:built
      Environment:
        Variables:
          QUARKUS_PROFILE: "integration-test"
          ELN_API_SECRET: "integrationTestsAPISecret"
          QUARKUS_LOG_CONSOLE_FORMAT: "[REPORTS] %d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
          QUARKUS_LOG_LEVEL: INFO # DEBUG
          QUARKUS_LOG_CATEGORY__NET_SF_JASPERREPORTS__LEVEL: INFO
      Events:
        InternalAPI:
          Type: HttpApi
          Properties:
            Path: /internalapi/reports/{proxy+}
            Method: ANY

  SignatureLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: indigoeln/signature-lambda:built
      Environment:
        Variables:
          QUARKUS_PROFILE: "integration-test"
          QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://172.17.0.1:25432/signature"
          QUARKUS_DATASOURCE_USERNAME: "eln"
          QUARKUS_DATASOURCE_PASSWORD: "eln"
          ELN_API_SECRET: "integrationTestsAPISecret"
#          ELN_SIGNATURE_KEYSTORE_PATH: "/keystore.p12"
          ELN_SIGNATURE_KEYSTORE_PASSWORD: "1234"
          QUARKUS_LOG_CONSOLE_FORMAT: "[SIGNATURE] %d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
          QUARKUS_REST_CLIENT_ELN_INTERNAL_API_URL: "http://172.17.0.1:28080"
          QUARKUS_REST_CLIENT_LOGGING_SCOPE: "request-response"
          QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT: "9999"
          QUARKUS_REST_CLIENT_EXTENSIONS_API_SCOPE: "all"
          QUARKUS_LOG_LEVEL: INFO # DEBUG
      Events:
        API:
          Type: HttpApi
          Properties:
            Path: /api/signature/{proxy+}
            Method: ANY
