sonar.projectKey=Indigo-ELN-Frontend
sonar.projectName=Indigo ELN Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=src/environments/**,**/*.spec.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/indigo-frontend/lcov.info
