quarkus.package.jar.type=legacy-jar

quarkus.native.enabled=true
quarkus.native.container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25

quarkus.native.resources.includes=db/migration/*,*.jpg,keystore.p12

quarkus.package.jar.enabled=false

quarkus.ssl.native=true
