server {
    listen 80;
    server_name localhost;

    client_max_body_size 50m;

    location /api/eln/ {
        proxy_pass http://eln-aws:8080;
        proxy_set_header Host $host;
    }
    location /internalapi/eln/ {
        proxy_pass http://eln-aws:8080;
        proxy_set_header Host $host;
    }
    location /api/signature/ {
        proxy_pass http://signature-aws:8080;
        proxy_set_header Host $host;
    }
    location /internalapi/reports/ {
        proxy_pass http://reports-aws:8080;
        proxy_set_header Host $host;
    }
}
