services:
  postgres:
    image: public.ecr.aws/m5k0g6n7/indigoeln/indigo-eln-postgres:latest
    environment:
      - POSTGRES_USER=eln
      - POSTGRES_PASSWORD=eln
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eln"]
      start_period: 60s
  eln-lambda:
    image: indigoeln/eln-lambda:built
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - "AWS_LAMBDA_RUNTIME_API=172.17.0.1:20001"
      - "QUARKUS_PROFILE=integration-test"
      - "QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/eln"
      - "QUARKUS_DATASOURCE_USERNAME=eln"
      - "QUARKUS_DATASOURCE_PASSWORD=eln"
      - "QUARKUS_LOG_CONSOLE_JSON_ENABLED=false"
      - "ELN_COGNITO_USER_POOL_ID=xxx"
      - "ELN_API_SECRET=xxx"
      - "ELN_INTERNAL_API_SECRET=xxx"
#      - "QUARKUS_REST_CLIENT_REPORTS_API_URL=http://17.17.0.1:28080"
      - "QUARKUS_REST_CLIENT_REPORTS_API_URL=http://reports-service:28081"
      - "QUARKUS_REST_CLIENT_LOGGING_SCOPE=request-response"
      - "QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT=9999"
      - "QUARKUS_REST_CLIENT_EXTENSIONS_API_SCOPE=all"
      - "QUARKUS_LOG_LEVEL=info"
#  reports-lambda:
#    build:
#      context: ../reports/reports-lambda
#      dockerfile: src/main/docker/Dockerfile.legacy-jar
#    environment:
#      - "AWS_LAMBDA_RUNTIME_API=172.17.0.1:20002"
#      - "QUARKUS_PROFILE=integration-test"
#      - "QUARKUS_LOG_CONSOLE_JSON_ENABLED=false"
#      - "ELN_API_SECRET=xxx"
#      - "QUARKUS_LOG_LEVEL=debug"
#    ports:
#      - 5005:5005
  reports-service:
    image: indigoeln/reports-service:built
    environment:
      - "QUARKUS_PROFILE=integration-test"
      - "QUARKUS_LOG_CONSOLE_JSON_ENABLED=false"
      - "ELN_API_SECRET=xxx"
      - "QUARKUS_LOG_LEVEL=info"
    ports:
      - 28081:8080
