quarkus.package.jar.type=legacy-jar

quarkus.container-image.build=true
quarkus.container-image.group=indigoeln
quarkus.container-image.name=reports-lambda
quarkus.container-image.tag=built

quarkus.native.enabled=false
