quarkus.package.jar.type=legacy-jar

quarkus.container-image.group=indigoeln
quarkus.container-image.name=reports-lambda
quarkus.container-image.tag=built

quarkus.snapstart.enable=true
# integration tests fail to run with quarkus.container-image.build=true
# !!!
quarkus.container-image.build=true
#quarkus.container-image.build=false
#quarkus.native.enabled=true
quarkus.native.enabled=false
#quarkus.native.container-build=true
#quarkus.native.remote-container-build=true
#quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21

#quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna\
#,--initialize-at-run-time=net.sf.jasperreports\
#,--initialize-at-run-time=net.sf.jasperreports.pdf\
#,--initialize-at-run-time=net.sf.jasperreports.renderers\
#,--initialize-at-run-time=net.sf.jasperreports.engine.util\
#,--initialize-at-run-time=com.ibm.icu.lang\
#,--initialize-at-run-time=net.sf.jasperreports.pdf.JRPdfExporter[$InternalImageProcessor\
# #,--strict-image-heap\
#,-J--add-opens=java.base/java.nio=ALL-UNNAMED\
#,-J--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED\
#,-H:+JNI
#,-Djna.debug_load=true\
#,-J-Djna.debug_load=true\
#,-H:Log=registerResource:5

#quarkus.native.resources.includes=reports/**,*.jasper,reports/ExperimentReport.jasper

# also:
# -g - generate debug info
# --enable-monitoring - enable stack trace, JFR, heap dump and other JVM features
#quarkus.package.jar.enabled=false

quarkus.datasource.devservices.port=15433
%integration-test.quarkus.flyway.migrate-at-start=true
%integration-test.quarkus.http.port=8085
quarkus.http.test-port=8084

quarkus.ssl.native=true

quarkus.test.integration-test-profile=integration-test
quarkus.test.native-image-profile=integration-test
%integration-test.quarkus.log.console.json.enabled=false

quarkus.log.min-level=TRACE
quarkus.log.level=TRACE
