quarkus.native.enabled=true
quarkus.package.jar.enabled=false

quarkus.native.resources.includes=reports/*

# Regenerate report classes again; it's done in reports-core, but generated classes are only registered by quarkus-jasperreports in reports-core.
quarkus.jasperreports.build.source=../reports-core/src/main/jasperreports
