quarkus.rest-client.reports-api.url=https://xxx/
quarkus.rest-client.reports-api.scope=jakarta.inject.Singleton
quarkus.rest-client.signature-api.url=https://xxx/
quarkus.rest-client.signature-api.scope=jakarta.inject.Singleton
quarkus.rest-client.signature-api2.url=https://xxx/
quarkus.rest-client.signature-api2.scope=jakarta.inject.Singleton
eln.internal.api.secret=xxx
