entryPoints:
  web:
    address: ":80"
    asDefault: true
  traefik:
    address: ":8090"

api:
  insecure: true

providers:
  file:
    filename: /etc/traefik/services.yaml

#log:
#  level: DEBUG

#experimental:
#  plugins:
#    traefik-oidc-auth:
#      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
#      version: "v0.7.0"
