#quarkus.security.security-providers=BC
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.path=/openapi/signature
quarkus.swagger-ui.path=/swagger/signature

quarkus.cognito-user-pools.devservices.enabled=false
