#quarkus.security.security-providers=BC
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.path=/openapi/signature
quarkus.swagger-ui.path=/swagger/signature

quarkus.datasource.devservices.port=15435
#quarkus.hibernate-orm.datasource

eln.cognito.user-pool-id=
quarkus.cognito-user-pools.devservices.enabled=false
quarkus.http.limits.max-form-attribute-size=4M
