quarkus.container-image.build=true
quarkus.container-image.group=indigoeln
quarkus.container-image.name=reports-service
quarkus.container-image.tag=built

# TODO
quarkus.oidc.enabled=false

quarkus.test.integration-test-profile=integration-test
quarkus.test.native-image-profile=integration-test
