quarkus.smallrye-openapi.path=/openapi/eln
quarkus.swagger-ui.path=/swagger/eln

quarkus.datasource.devservices.port=15432
quarkus.datasource.devservices.image-name=public.ecr.aws/m5k0g6n7/indigoeln/indigo-eln-postgres:latest
#quarkus.test.enable-callbacks-for-integration-tests=true # don't enable, breaks integration tests!

eln.cognito.user-pool-id=
# !!! switch to CognitoExternalUserService when AWS networking is resolved
#quarkus.arc.selected-alternatives=com.epam.indigoeln.eln.service.CognitoExternalUserService
quarkus.arc.selected-alternatives=com.epam.indigoeln.eln.service.FakeExternalUserService
%devtest.quarkus.arc.selected-alternatives=com.epam.indigoeln.eln.service.FakeExternalUserService
