quarkus.smallrye-openapi.path=/openapi/eln
quarkus.swagger-ui.path=/swagger/eln

quarkus.datasource.devservices.port=15432

eln.cognito.user-pool-id=
quarkus.cognito-user-pools.devservices.enabled=false

quarkus.rest-client.pubchem.uri=https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/
