FROM registry.access.redhat.com/ubi9/openjdk-21

USER root

ENV LANGUAGE='en_US:en'

COPY build/function.zip /var/task/function.zip
RUN cd /var/task && jar -xf function.zip && rm function.zip

ENTRYPOINT [ \
    "/usr/bin/java", \
    "-cp", \
    "/var/task:/var/task/lib/*", \
    "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", \
    "--add-opens", "java.base/java.lang=ALL-UNNAMED", \
    "--add-opens", "java.base/jdk.internal.misc=ALL-UNNAMED", \
    "com.epam.indigoeln.lambda.LambdaClient" \
]
