%dev.quarkus.config.profile.parent=devtest
%test.quarkus.config.profile.parent=devtest
%integration-test.quarkus.config.profile.parent=devtest

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true

quarkus.log.level=INFO
quarkus.log.category."com.epam".level=DEBUG
quarkus.log.console.json.exception-output-type=formatted

quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.physical-naming-strategy=io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
quarkus.hibernate-orm.validate-in-dev-mode=false
jakarta.persistence.schema-generation.database.action=none
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.mapping.format.global=ignore
# TODO is it needed?
#mp.jwt.verify.issuer=https://keycloak.indigoeln.local:8443/realms/indigo-eln
#mp.jwt.verify.publickey.location=https://keycloak.indigoeln.local:8443/auth/realms/indigo-eln/protocol/openid-connect/certs
#smallrye.jwt.client.tls.trust-all=true

quarkus.swagger-ui.always-include=true
quarkus.keycloak.devservices.enabled=false

quarkus.datasource.devservices.image-name=public.ecr.aws/m5k0g6n7/indigoeln/indigo-eln-postgres:latest

%devtest.jakarta.persistence.schema-generation.database.action=validate
%devtest.quarkus.hibernate-orm.database.generation=validate
%devtest.quarkus.flyway.migrate-at-start=true
%integration-test.quarkus.flyway.migrate-at-start=true

# logging
#%devtest.quarkus.log.level=DEBUG
%devtest.quarkus.log.level=INFO
%devtest.quarkus.log.min-level=DEBUG
%devtest.quarkus.log.category."com.epam".level=DEBUG
%devtest.quarkus.log.console.json.enabled=false
%devtest.quarkus.log.file.json.enabled=false
%devtest.quarkus.log.console.darken=1
quarkus.test.display-test-output=true
quarkus.test.continuous-testing=enabled
%devtest.quarkus.rest-client.logging.scope=request-response
%devtest.quarkus.rest-client.logging.body-limit=1000
%devtest.quarkus.rest-client.extensions-api.scope=all

# logging hibernate
#%devtest.quarkus.hibernate-orm.log.sql=true
#%devtest.quarkus.hibernate-orm.log.bind-parameters=true
