%dev.quarkus.config.profile.parent=devtest
%test.quarkus.config.profile.parent=devtest
%integration-test.quarkus.config.profile.parent=devtest

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true

quarkus.log.level=INFO
quarkus.log.category."com.epam".level=DEBUG
quarkus.log.console.json.exception-output-type=formatted

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.keycloak.devservices.enabled=false

quarkus.datasource.devservices.image-name=public.ecr.aws/m5k0g6n7/indigoeln/indigo-eln-postgres:latest

eln.cognito.user-pool-id=

%dev.eln.api.secret=secret
%test.eln.api.secret=secret

# logging
#%devtest.quarkus.log.level=DEBUG
%devtest.quarkus.log.level=INFO
%devtest.quarkus.log.min-level=DEBUG
%devtest.quarkus.log.category."com.epam".level=DEBUG
%devtest.quarkus.log.console.json.enabled=false
%devtest.quarkus.log.file.json.enabled=false
%devtest.quarkus.log.console.darken=1
quarkus.test.display-test-output=true

# logging rest client
quarkus.log.category."feign".level=INFO
#%devtest.quarkus.log.category."feign".level=DEBUG
#%devtest.quarkus.rest-client.logging.scope=request-response
#%devtest.quarkus.rest-client.logging.body-limit=1000
#%devtest.quarkus.rest-client.extensions-api.scope=all

# logging authorization
quarkus.log.category."com.epam.indigoeln.eln.config.SecurityEventObserver".level=INFO
#%devtest.quarkus.log.category."com.epam.indigoeln.eln.config.SecurityEventObserver".level=DEBUG
