#quarkus.package.jar.type=legacy-jar

quarkus.snapstart.enable=false
# integration tests fail to run with quarkus.container-image.build=true
quarkus.container-image.build=false
quarkus.native.enabled=true
quarkus.native.container-build=true
#quarkus.native.remote-container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-24
#quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna
# !!! -g for debug
#quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna,

quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna\
,--add-opens=java.base/java.nio=ALL-UNNAMED\
,--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
# also:
# -g - generate debug info
# --enable-monitoring - enable stack trace, JFR, heap dump and other JVM features
quarkus.package.jar.enabled=false

quarkus.datasource.devservices.port=15433
%integration-test.quarkus.flyway.migrate-at-start=true
%integration-test.quarkus.http.port=8083
quarkus.http.test-port=8081

quarkus.container-image.jib.extra-files[0].path=build/nativelibs
quarkus.container-image.jib.extra-files[0].target-path-in-image=/nativelibs
quarkus.container-image.jib.extra-files[0].permissions=755
#quarkus.container-image.jib.environment-variables.LD_LIBRARY_PATH=/indigolibs/linux-x86_64
quarkus.container-image.jib.environment-variables.NATIVE_LIB_PATH=/indigolibs
#quarkus.native.java-library-path=build/extractedIndigoLibs/linux-x86_64

quarkus.ssl.native=true

quarkus.test.integration-test-profile=integration-test
quarkus.test.native-image-profile=integration-test
%integration-test.quarkus.log.console.json.enabled=false
