quarkus.native.enabled=true
quarkus.package.jar.enabled=false

quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna\
,-J--add-opens=java.base/java.nio=ALL-UNNAMED\
,-J--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED

quarkus.native.resources.includes=db/data/*
