#quarkus.package.jar.type=legacy-jar

quarkus.snapstart.enable=false
# integration tests fail to run with quarkus.container-image.build=true
quarkus.native.enabled=true
quarkus.native.container-build=true
#quarkus.native.remote-container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25

quarkus.container-image.build=true
quarkus.container-image.group=indigoeln
quarkus.container-image.name=eln-lambda
quarkus.container-image.tag=built

quarkus.test.integration-test-artifact-type=native

quarkus.native.additional-build-args=--initialize-at-run-time=com.sun.jna\
,-J--add-opens=java.base/java.nio=ALL-UNNAMED\
,-J--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED

quarkus.native.resources.includes=db/data/*

# also:
# -g - generate debug info
# --enable-monitoring - enable stack trace, JFR, heap dump and other JVM features
quarkus.package.jar.enabled=false

quarkus.ssl.native=true

quarkus.test.integration-test-profile=integration-test
quarkus.test.native-image-profile=integration-test
